Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 205
      MemorySize: 10240
      Handler: helloworld.App
      CodeUri: C:\Users\denis\IdeaProjects\AWS-API-Hibernate\HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64